function yn = validMarkerSet(ms)
    yn = false;
    if sum(sum(ms.hand)) ~= 4 && ...
       sum(sum(ms.elbow)) ~= 4 && ...
       sum(sum(ms.neck)) ~= 4   && ...
       sum(sum(ms.chest)) ~= 4  && ...
       sum(sum(ms.waist)) ~= 4   && ...      
       sum(sum(ms.leftShoulder)) ~= 4
    
        yn = true;
    end
end

function yn = validMarkerSet_Correct(ms)
    yn = false;
    if sum(sum(ms.hand)) ~= 4 && ...
       sum(sum(ms.elbow)) ~= 4 && ...
       sum(sum(ms.rightShoulder)) ~= 4 && ...
       sum(sum(ms.neck)) ~= 4   && ...
       sum(sum(ms.chest)) ~= 4  && ...
       sum(sum(ms.waist)) ~= 4   && ...      
       sum(sum(ms.leftShoulder)) ~= 4
    
        yn = true;
    end
end
